// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd9zBa51LMxESp2U3nn0fwmwRqR06yL_0',
    appId: '1:615843848836:web:5771b05bc22e79357ed8d1',
    messagingSenderId: '615843848836',
    projectId: 'fir-fermer',
    authDomain: 'fir-fermer.firebaseapp.com',
    storageBucket: 'fir-fermer.firebasestorage.app',
    measurementId: 'G-YCYT95JW8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtXx1ReL1829wX1maZzKv3dyg2eo2mKXc',
    appId: '1:615843848836:android:acdf1bb55ee1e9c97ed8d1',
    messagingSenderId: '615843848836',
    projectId: 'fir-fermer',
    storageBucket: 'fir-fermer.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXagWCxSQxDZia0RiFBliPjM1XnGhaiTo',
    appId: '1:615843848836:ios:49b75cac63bbf67f7ed8d1',
    messagingSenderId: '615843848836',
    projectId: 'fir-fermer',
    storageBucket: 'fir-fermer.firebasestorage.app',
    iosBundleId: 'kz.fermerplus.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXagWCxSQxDZia0RiFBliPjM1XnGhaiTo',
    appId: '1:615843848836:ios:788b3143c7d45e7a7ed8d1',
    messagingSenderId: '615843848836',
    projectId: 'fir-fermer',
    storageBucket: 'fir-fermer.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd9zBa51LMxESp2U3nn0fwmwRqR06yL_0',
    appId: '1:615843848836:web:e210e5cdf608708b7ed8d1',
    messagingSenderId: '615843848836',
    projectId: 'fir-fermer',
    authDomain: 'fir-fermer.firebaseapp.com',
    storageBucket: 'fir-fermer.firebasestorage.app',
    measurementId: 'G-6LRXVSBSL3',
  );
}
